version: '3.9'
volumes:
  pgdata:
  pgadmin-data:


services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin     

        
  trading_app:
    image: ghcr.io/fpv-bughunters/app-be:main
    container_name: trading_app
    ports:
      - 8081:8080
    volumes:
      - ./config:/config
    
    
    

  
